appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p9ojDIQZi7Op8QB42MTssw2RTjr1HsO8fnta+2Ypui+2wIKnR7QzG+iTrQ/lMFaunKpRvX3m1xxaU8IRE/p8QK2Lp4tfd196IkMr5NRL+b+dHSJOvLcRlTZnS3Lf2CK0U4c+AgXxTTnhIGRHw4/Zhq7mBUxgica2jQYgA0HSGztO4Oz6NYGGQq6XcygWQJDE4kjhU8zZo86l+yTxH+0dq5o03HmQqa4OflDTM9k0a6Yu+f3VuA76o4Vo+HR08wwiYYN7YltBvkOTAD/hw7hQcDzLK46kUokGOUydzXTgXg+4bMLw68GCric1vTwn+HTuZ9O7QGcaSHagoAQdCW2uMhv5tZk1d39bzc7dUnulTVdhUfxl1ZFtUc38W/GW96knyHZdiAyYPiUQH0wz1lnI6gcCDd+xBSiRue4ajshlS2gLRaky0DD3g76o1Wr4C/vneP9ANPX6gU+RAFNfJbckqta3EZastfYa0UmgZoOCYOyLPxQ/ef1t3dEG9yycyYUjOVMp4RqLSUupjWLUbIWDTkhULFWcTeYy+N3n1y+80DyWSJFaE8YxsN1ScmmccpN5bMtR1BvVgYv1qw2hOJdYQ9rLXU6Ec0eVL4gFFjCXKDXcxcPwGFD+0sxG+WtV8NacOjgIGMHPAYraMJhizMRfBfh1s0crWodh5pEOBn1CewQ=}
